# @package _global_
defaults:
  - override hydra/job_logging: 'disabled'

task_type: IMPL_CORRECTNESS
log_dir: ".logs/eval_few_shot_impl_few_shot_proof_kimina"
exp_name: "few_shot_impl_few_shot_proof_kimina"
impl_generation_strategy: "ImplGenerator"
problems_to_solve: [53]
k: 1
timeout_in_secs: 600
params:
  proof_dump_file_path: "proofs.txt"
  num_implementation_samples: 1000
  num_proof_plan_samples: 1000
  uses_copra_prover: false
  impl_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/baselines/system/FewShotImplGeneration.md"
    example_prompt_path: "src/clever_prover/prompts/baselines/examples/FewShotImplGeneration.md"
    max_tokens_per_action: 5000
    max_history_messages: 0
    end_tokens: ["[END]"]
  impl_model_settings:
    model_name: "gpt-5-mini"
    secret_path: ".secrets/openai_key.json"
    temperature: 0.75
  prover_prompt_settings:
    system_prompt_path: "src/clever_prover/prompts/baselines/system/FewShotImplProofGeneration.md"
    example_prompt_path: "src/clever_prover/prompts/baselines/examples/FewShotImplProofGeneration.md"
    max_tokens_per_action: 7500
    max_history_messages: 0
    end_tokens: ["[END]"]
  prover_model_settings:
    model_name: "vllm:AI-MO/Kimina-Prover-Distill-1.7B"
    secret_path: ".secrets/openai_key.json"
    temperature: 0.75
  proof_planner_prompt_settings: null
  proof_planner_model_settings: null
  impl_planner_model_settings: null
  impl_planner_prompt_settings: null